---
blank_issues_enabled: false
contact_links:
  - name: SignToolUI Community Support
    url: https://github.com/michaelmsonne/SignToolUI/discussions
    about: Please ask and answer questions here.
